<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>PDF_Creation</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\Anni Christmas.jpg" />
    <None Remove="images\Petcare Logo.png" />
    <None Remove="images\petcarelogo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2025.7.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\Anni Christmas.jpg" />
    <Resource Include="images\Petcare Logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\petcarelogo.png" />
  </ItemGroup>

</Project>
